### ISSUE TITLE
OS X Homebrew lua5.1 uses -llua5.1 not -llua

### ISSUE THREAD

**Issue by Investocat** [aarzilli/golua#32]
Now that homebrew moved lua to 5.2, they provide a lua5.1 pacakge. The issue is that the library is now called the same as it is on linux/windows, so we need to edit lua.go to get it to compile correctly.

Could we modify darwin to use 5.1 or add a 5.1 override similar to the llua/luaa tags that exist now?

**Comment by aarzilli** [comment]
I stopped using OS X entirely 5 years ago. Back then the preferred method to install open source on OS X was MacPorts but these days I see Homebrew mentioned far more often than MacPorts.
If this is really the preferred method to install lua on a mac then I'll take a pull request, I'm not making the change myself because I have no way of testing it.

**Comment by aarzilli** [comment]
Closed via e80696fd9775a75421bc921a80982d345bb2ad70
