### ISSUE TITLE
4 byte per luastate memory leak

### ISSUE THREAD

**Issue by shanemhansen** [aarzilli/golua#44]
As part of making golua compatible with go1.6, a global, never shrinking array of luastate objects was addeed, with the note "leaks 4 bytes per lua state".
https://github.com/aarzilli/golua/commit/1074bd50a84be62f322d7b2cf8109e1f1801bfeb

Any ideas on how to get around that?

**Comment by shanemhansen** [comment]
Would you be interested in a PR that did something like qo-qml?: https://github.com/go-qml/qml/commit/826359aa6875bedc3fe6b0e4b481bb9e487acc46

**Comment by aarzilli** [comment]
In `registerGoState` instead of always appending at the end loop through `goStates` and pick one entry that is nil, only append at the end if none is found. It will make creating a new state O(n) but won't leak memory anymore.

The solution that go-qml uses is also acceptable, I would merge a PR for this.
