### ISSUE TITLE
ToThread implementation

### ISSUE THREAD

**Issue by glycerine** [aarzilli/golua#65]
I did an implementation of ToThread. It *appears* to work, but I would glad to have it reviewed by someone with more experience. If it seems satisfactory, it might be pleasant to add it to golua.

In place https://github.com/aarzilli/golua/blob/master/lua/lua.go#L568 of the TODO, I wrote:

~~~
// lua_tothread
func (L *State) ToThread(index int) *State {
    s := &State{s: (*C.lua_State)(unsafe.Pointer(C.lua_tothread(L.s, C.int(index))))}
    registerGoState(s)
    return s
}
~~~

In particular, is the `registerGoState(s)` call the correct thing to do?  I'm not at all certain.  When I register fmt.Printf with one thread, invoking it calls MakeChan registered with the main vm, so it seems that wires are getting crossed.  But that might just be a different bug elsewhere.

**Comment by glycerine** [comment]
Q: is a coroutine really equivalent to a whole golua.State? I kind of assumed, perhaps naively, that a golua.State would hold many corotines, since they all refer to the same _G global env table, and can refer to the same upvals/closures/nested scopes, etc.  But the Lua API seems to think of them as whole States... weird.

**Comment by aarzilli** [comment]
I've never looked at lua's coroutines (I don't see why it's useful to have a greenthreads model implemented on top of go's greenthread model) but I don't think this is enough. If tothread returns a lua_State we already know about we should return the corresponding lua.State rather than a new object every time. This is also not going to work if we have a non-empty registry.

**Comment by glycerine** [comment]
Thanks @aarzilli !

> This is also not going to work if we have a non-empty registry.

Tell me more about this, if you would. I would like to design a solution here, but I don't understand the registry and its purpose/how I should be using it.

> I've never looked at lua's coroutines (I don't see why it's useful to have a greenthreads model implemented on top of go's greenthread model) but I don't think this is enough. 

Yeah. I thought the same at first. So I tried just the simplest thing -- 1:1 goroutine:goroutine; i.e. just use an actual goroutine to represent a goroutine in my Go interpreter, but it turns out that approach was defeated by closures. In brief, the upvalues shared between coroutines don't need synchronization in the single threaded Lua vm, but they do need synchronization when shared by actually parallel goroutines. And while Lua gives us ways to list and replace the upvalues, there's no lock inside the Lua vm that we can set before touching those upvalues.

> If tothread returns a lua_State we already know about we should return the corresponding lua.State rather than a new object every time. 

Good point. My patch above does return the old lua_State, but in a new wrapper each time. The wrapper should probably be reused too.  Perhaps that is the idea of the registry?

**Comment by glycerine** [comment]
So I'm wondering if the State shouldn't share registry and freeIndices, like this
~~~
func (L *State) ToThread(index int) *State {
    s := &State{
        s:           (*C.lua_State)(unsafe.Pointer(C.lua_tothread(L.s, C.int(index)))),
        registry:    L.registry,
        freeIndices: L.freeIndices,
    }
    s.Index = uintptr(unsafe.Pointer(s))
    registerGoState(s)
    return s
}
~~~

**Comment by aarzilli** [comment]
> Tell me more about this, if you would. I would like to design a solution here, but I don't understand the registry and its purpose/how I should be using it.

We can't [save go pointers in C memory](https://golang.org/cmd/cgo/) so instead, if we want to publish some go object (be it a go function or a go struct) to lua, we register it in [the registry](https://github.com/aarzilli/golua/blob/master/lua/golua.go#L34) and publish the index to the registry entry to lua instead, as light userdata.

Let's say you want to publish a go function to lua, you call L.PushGoFunction, what happens is that PushGoFunction

1. Saves a pointer (really an interface) to the function in L.registry[idx]
2. pushes idx to L.s (the *C.lua_State) as light userdata
3. configures the metatable of the newly created userdata to make it look like a function (i.e. it sets its __call attribute) -- look for MT_GOFUNCTION in the source for this

when lua tries to call this published function

1. it finds the __call attribute into the metatable for the userdata, which points to the C function callback_function
2. callback_function checks the *lua registry* (which is different from the State.registry) for the "k" key where we store the go state index when the state is created
3. We use the gostateindex to get the lua.State associated to the C.lua_State we are running, call it "L"
4. We convert the light userdata back into an integer index idx and look up L.registry[idx] for the function

Note that a registration in the registry, isn't permanent, if lua garbace collects our userdata object the registry association will be deleted (look for gchook_wrapper in the source)

your solutions (both of them) aren't going to work for multiple reasons:

* in the first one you aren't sharing the registry, in the second one you are copying it. Either way the registry of the two lua.State are going to diverge, in the first case they are diverged from the start, in the second case it's going to happen the first time we reallocate one to grow it
* the setup of a newly created lua_State is going to be wrong until it's registered. It will look like it works but if you call a go function, the go side will believe that the original lua coroutine made the call. Worse, I suspect that the LUA_REGISTRY is going to be shared between lua coroutines which means that calling registerGoState on the new coroutine will break the old coroutine.
* That's not even getting into actually running multiple coroutines, I see that there is a yield function for example. Now, yield to my ears sounds a lot like longjmp, I might be wrong on this, but if I'm right that's a world of pain with cgo.

The first point is easy to fix, the second one is very hard, the third might border impossibility. My gut feeling is that coroutine support with golua will never happen, but I haven't proved it beyond all doubt, so you could prove me wrong.

> So I tried just the simplest thing -- 1:1 goroutine:goroutine; i.e. just use an actual goroutine to represent a goroutine in my Go interpreter

If I understand correctly what you are doing is taking go source, transpiling it to lua code then running it into a lua VM. I don't think that's going to work, even if you solve all the problems above. 

If you turn a goroutine into a lua coroutine all your lua coroutines will run on top of a single goroutine, which means that I/O calls will appear to be blocking to your interpreted go, i.e. the first time one of your interpreted goroutine makes a call to fmt.Printf every other interpreted goroutine will be blocked until the call to fmt.Printf finishes. That's not the expected behavior for a go program and goroutines without this property are basically useless.

The only way around this is to reimplement the entire go runtime in lua.

**Comment by glycerine** [comment]
This is super helpful, Alessandro. Thank you!

> If I understand correctly what you are doing is taking go source, transpiling it to lua code then running it into a lua VM.

That is correct.

> The only way around this is to reimplement the entire go runtime in lua.

GopherJS provides a counter-example. It is the basis for my implementation (I'm changing it from producing Javascript to producing Lua, with minor tweaks, but the framework is all GopherJS). It uses another way; translating everything into Javascript, and handling blocking calls.

> goroutines without this property are basically useless.

In terms of getting performance it may be useless, but it is far from useless for the aim of an interpreter is to get correctness, and then later the compiler can be applied to get performance. Some things may not work exactly the same, I'm over it. 1% of things may not work in the hybrid world, but meh, still tons of utility to be had.

Now I am going for a hybrid, because I want *some* performance in my interpreter. But that means I'm willing to accept some limitations. Like not getting to longjmp over a cgo transition on the call stack. You are right that won't work, (and at least PUC Lua uses setjmp/longjmp, LuaJIT probably a custom assembly version of the same idea) but its only needed when going from Lua -> binary Go -> Lua, so in hybrid code we simply forbid that, and  Lua -> binary Go never get to call back via CGO into Lua again; i.e. you won't be able to pass in function pointers.  Still this is quite useful for my purposes.  Because the Lua side can still deal in proxies to Go all it wants.

Anyway, super helpful to have the critique to sharpen the design!

1) is just a pointer, easily fixed, as you say.

2)
> the setup of a newly created lua_State is going to be wrong until it's registered. It will look like it works but if you call a go function, the go side will believe that the original lua coroutine made the call.

This is the critical part to fix. I'll need to do this.

 > Worse, I suspect that the LUA_REGISTRY is going to be shared between lua coroutines which means that _calling registerGoState on the new coroutine will break the old coroutine._ <emphasis mine>

I think that's right, that LUA_REGISTRY is shared, by Lua's design.

I don't follow  the breaking part. registerGoState looks like this
~~~
func registerGoState(L *State) {
    goStatesMutex.Lock()
    defer goStatesMutex.Unlock()
    L.Index = uintptr(unsafe.Pointer(L))
    goStates[L.Index] = L
}

L, the pointer to the outer wrapper *State, is a distinct pointer for every new coroutine; assuming the 2nd implementation proposed above:

~~~
func (L *State) ToThread(index int) *State {
    s := &State{
        s:           (*C.lua_State)(unsafe.Pointer(C.lua_tothread(L.s, C.int(index)))),
        registry:    L.registry,
        freeIndices: L.freeIndices,
    }
    s.Index = uintptr(unsafe.Pointer(s))
    registerGoState(s)
    return s
}
~~~
so L.Index is unique for each registered coroutine. How would that break an older coroutine?  I'm sure I'm just missing something.

Thanks again!

**Comment by aarzilli** [comment]
> I don't follow the breaking part. registerGoState looks like this

that's only half of the setup, the other half is clua_setgostate/clua_initstate (in particular clua_setgostate)

**Comment by glycerine** [comment]
> that's only half of the setup, the other half is clua_setgostate/clua_initstate (in particular clua_setgostate)

Great! thank you.

**Comment by glycerine** [comment]
> The only way around this is to reimplement the entire go runtime in lua.

Arg. I misread this at first.  That is actually the plan. The scheduler is 98% done. It handles blocking sends and receives on channels, selects, spawning new goroutines right now. Timeouts aren't done because I don't have the time pacakge, and the only other part that doesn't work like Go (currently), is the noticing of blocking io calls after 10 msec and starting new threads to keep liveness.  I haven't thought very hard about how to handle that.

**Comment by glycerine** [comment]
> the setup of a newly created lua_State is going to be wrong until it's registered. It will look like it works but if you call a go function, the go side will believe that the original lua coroutine made the call.

I think this is just a matter of having the go side call `coroutine.running()` and then using the stack that's returned (which is the currently active coroutine stack). The 2nd return is true iff its the main thread, but I don't even think that's needed.

> that's only half of the setup, the other half is clua_setgostate/clua_initstate (in particular clua_setgostate)

I'm thinking there's no need for new coroutines to replace 'k' at all in the lua registry. I could be wrong, but I don't see why that would be needed at all, given the `coroutine.running()` approach above.

**Comment by glycerine** [comment]
I have a passing test showing that this can be made to work. 

The `coroutine.running()` idea didn't work but rather just storing a map from thread to index in 'k'/the Lua registry.

I also had to store a pointer to the main thread in the Lua registry, so that coroutines could find their main (in the absence of an API in Lua to locate the main coroutine from a non-main one); but that's a minor bit of extra prep work.

**Comment by glycerine** [comment]
Coroutines are working and tested on my fork. 

https://github.com/glycerine/golua  in particular as of https://github.com/glycerine/golua/commit/a1792f6a43dee4beccca3218989d383c96cbbc74

This is quite a substantial change, so it may not be desirable to merge it here. I'll leave that to @aarzilli 's discretion. It may change further as I now commence work on getting the Luar layer above it working too.

Thanks again, Alessandro, for your guidance around the issues.
